import "pkg:/source/roku_deeplinking_screen/DeeplinkingControllerVM.bs"
function init()

  m.top.isForcingMenuHidden = true
  m.top.isManagingPrehooks = true
end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Overridden methods
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function createVM()
  m.logInfo("m.top.riversJson", m.top.riversJson)
  vm = new DeeplinkingControllerVM(m.top.riversJson)
  MVMM.initializeBindings(true)
  mv.initializeView(m.top.findNode("screenContainer"))
  return vm
end function

function getDefaultRiversJson()
  m.logInfo("getDefaultRiversJson")

  return {
    "id": "deeplinkingcontroller"
    "styles": {
      "logo_w": "350",
      "logo_x": "100",
      "family": "FAMILY_1",
      "logo_y": "33",
      "background_color": "#ff000000",
      "logo_h": "100",
      "style_json": "{}",
      "logo_url": "loginLogo.png",
      "background_url": "pkg:/asset-bundle/background.jpg"
    }
  }
end function
