import "pkg:/source/roku_modules/log/LogMixin.brs"
import "pkg:/source/entitlements_item_loader_prehook/EntitlementsItemLoader.bs"


function init()
  m.top.functionName = "execRunLoop"
end function


function execRunLoop()
  m.log = new log.Logger("EntitlementsItemLoaderTask")
  m.log.method("execRunLoop")

  resolver = new EntitlementsItemLoader()
  m.top.output = resolver.execute()
end function