import "pkg:/source/roku_search_screen/FullScreenSearchVM.bs"

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Initialization
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function Init()
  m.top.isFullScreen = true
end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Overridden
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function createVM()
  return new FullScreenSearchVM(m.top.riversJson)
end function
