'@TestSuite [RCLSVMT] RegcodeLoginScreenVM Tests
namespace RCLSVMT

'@BeforeEach
function beforeEach()
  localStore = createObject("roSGNode", "ZSessionStore")
  modelLocator = createObject("roSGNode", "ModelLocator")
  modelLocator.addfields({ "ZPLocalStore": localStore })
  TU.setModelLocator(modelLocator)
  
  riversJson = {
    "id": "regcodeScreen"
    styles: {
    }
  }
  
  m.vm = new RegcodeLoginScreenVM(riversJson)
  m.analyticsManager = { "id" : "analyticsManager" }
  m.vm.analyticsManager = m.analyticsManager
  
  m.vm.initialize()
end function

'@AfterEach
function afterEach()
  m.global.delete("zapp")
  TU.unsetModelLocator()
end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'@It tests onKeyPressBack
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

'@Test 
function onKeyPressBack()
  m.expectOnce(m.vm, "dismiss", ["cancel"])
  m.vm.onKeyPressBack()
  
end function

'TODO !!!
end namespace