import "pkg:/source/roku_modules/log/LogMixin.brs"
import "pkg:/source/generic_url_token_appender/GenericUrlTokenAppender.bs"
import "pkg:/source/roku_modules/maestro/core/Utils.brs"


function init()
  m.top.functionName = "execRunLoop"
end function


function execRunLoop()
  m.log = new log.Logger("GenericUrlTokenAppenderTask")
  m.log.method("execRunLoop")

  resolver = new GenericUrlTokenAppender()
  m.top.output = resolver.execute()
end function