import "pkg:/source/rLog/rLogMixin.brs"
import "pkg:/source/generic_url_token_appender/GenericUrlTokenAppender.bs"
import "pkg:/source/maestro/lib/Utils.bs"


function init()
  m.top.functionName = "execRunLoop"
end function


function execRunLoop()
  registerLogger("GenericUrlTokenAppenderTask")
  m.logMethod("execRunLoop")

  resolver = new GenericUrlTokenAppender()
  m.top.output = resolver.execute()
end function