import "pkg:/source/quick-brick-login-flow/FlowForgotPasswordScreenVM.bs"
import "pkg:/source/roku_modules/maestro/mx/VMTransformFunctions.brs"

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Initialization
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function init()
  m.top.isForcingMenuHidden = true
  initializeView(m.top.findNode("labelsGroup"))
  initializeView(m.top.findNode("controlsGroup"))
  initializeView(m.top.findNode("doneGroup"))
end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Overridden methods
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function createVM()
  vm = new FlowForgotPasswordScreenVM(m.top.riversJson)
  return vm
end function
