'@TestSuite [GAPT] GoogleAnalyticsPluginTests

namespace GAPT

'@BeforeEach
function beforeEach()
  config = {
    "tracking_id": "#t"
    "client_id": "#c"
  }
  m.modelLocator = createObject("roSGNode", "ModelLocator")
  
  TU.setModelLocator(m.modelLocator)
  m.pluginData = new BasePlugin({ "configuration_json": config, "identifier": "google_analytics_roku" })
  m.plugin = new GoogleAnalyticsPlugin(m.pluginData)
end function

'@AfterEach
function afterEach()
  TU.unsetModelLocator()
end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'@It tests constructor
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

'@Test constructor
function constructor()
  m.assertEqual(m.plugin.id, "google_analytics_roku")
  m.assertSubType(m.plugin.task, "GoogleAnalyticsTask")
  m.assertEqual(m.plugin.task.trackingId, "#t")
  m.assertEqual(m.plugin.task.clientId, "#c")
end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'@It tests start
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

'@Test start
function start()
  
  task = { "id" : "task" }
  m.plugin.task = task
  
  m.expectOnce(m.plugin, "setInstance", ["googleAnalyticsTask", task])

  m.plugin.start()
  m.assertEqual(m.plugin.task.control, "run")
end function

