import "pkg:/source/warning_message_screen_roku/WarningMessageScreenVM.bs"

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Initialization
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function init()
  m.top.isConsumingOriginEntry = true
  M_createNodeVars() 
end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Overridden methods
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function getControlName()
  return "WarmingMessageScreen"
end function

function createVM()
  vm = new WarningMessageScreenVM(m.top.riversJson)
  vm.originEntry = m.top.originEntry
  return vm
end function