import "pkg:/source/warning_message_screen_roku/WarningMessageScreenVM.bs"

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Overridden methods
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function createVM()
  vm = new WarningMessageScreenVM(m.top.riversJson)
  mv.setFocus(m.doneButton)
  return vm
end function

function onGainedFocus(isSelfFocused)
  if isSelfFocused
    mv.setFocus(m.doneButton)
  end if
end function