import "pkg:/source/warning_message_screen_roku/WarningMessageScreenVM.bs"

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Initialization
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function init()
  m.top.isConsumingOriginEntry = true
  m.top._styledControlIds = [
    "backgroundRect"
    "backgroundPoster"
    "logoPoster"
    "labelsGroup"
    "titleText"
    "descriptionText"
    "optional1Text"
    "doneButton"
  ]

end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Overridden methods
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function createVM()
  vm = new WarningMessageScreenVM(m.top.riversJson)
  vm.originEntry = m.top.originEntry
  mv.setFocus(m.doneButton)
  return vm
end function

function onGainedFocus(isSelfFocused)
  if isSelfFocused
    mv.setFocus(m.doneButton)
  end if
end function