import "pkg:/source/forgot_password_screen_roku/ForgotPasswordScreenVM.bs"

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Initialization
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function init()
  m.top.isConsumingOriginEntry = true
  m.top.isForcingMenuHidden = true
  mv.initializeView(m.top.findNode("labelsGroup"))
  mv.initializeView(m.top.findNode("controlsGroup"))
  mv.initializeView(m.top.findNode("doneGroup"))
end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Overridden methods
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function createVM()
  vm = new ForgotPasswordScreenVM(m.top.riversJson)
  return vm
end function
