import "pkg:/source/forgot_password_screen_roku/ForgotPasswordScreenVM.bs"
import "pkg:/source/roku_modules/maestro/mx/VMTransformFunctions.brs"

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Initialization
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function init()
  m.top.isConsumingOriginEntry = true
  m.top.isForcingMenuHidden = true
  initializeView(m.top.findNode("labelsGroup"))
  initializeView(m.top.findNode("controlsGroup"))
  initializeView(m.top.findNode("doneGroup"))
end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Overridden methods
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function createVM()
  vm = new ForgotPasswordScreenVM(m.top.riversJson)
  return vm
end function
