import "pkg:/source/general_text_screen_roku/GeneralTextScreenVM.bs"

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Initialization
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function init()
  m.top.isConsumingOriginEntry = true
end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Overridden methods
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function createVM()
  vm = new GeneralTextScreenVM(m.top.riversJson)
  vm.originEntry = m.top.originEntry
 mv.setFocus(m.doneButton)
  return vm
end function

function onGainedFocus(isSelfFocused)
  if isSelfFocused
   mv.setFocus(m.doneButton)
  end if
end function
