import "pkg:/source/general_text_screen_roku/GeneralTextScreenVM.bs"

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Initialization
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Overridden methods
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function createVM()
  vm = new GeneralTextScreenVM(m.top.riversJson)
  mv.setFocus(m.doneButton)
  return vm
end function

function onGainedFocus(isSelfFocused)
  if isSelfFocused
    mv.setFocus(m.doneButton)
  end if
end function
