import "pkg:/source/general_text_screen_roku/GeneralTextScreenVM.bs"

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Initialization
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function init()
  m.top.isConsumingOriginEntry = true
  m.top._styledControlIds = [
    "backgroundRect"
    "backgroundPoster"
    "logoPoster"
    "labelsGroup"
    "titleText"
    "descriptionText"
    "optional1Text"
    "doneButton"
  ] 

end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Overridden methods
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function getControlName()
  return "WarmingMessageScreen"
end function

function createVM()
  vm = new GeneralTextScreenVM(m.top.riversJson)
  vm.originEntry = m.top.originEntry
  setFocus(m.doneButton)
  return vm
end function

function onGainedFocus(isSelfFocused)
  if isSelfFocused
    setFocus(m.doneButton)
  end if
end function
