import "pkg:/source/quick-brick-epg-screen/QuickBrickEpgScreenVM.bs"
import "pkg:/source/roku_modules/maestro/mx/VMTransformFunctions.brs"

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Initialization
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function init()
  initializeView(m.top.findNode("screenContainer"))
end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Overridden methods
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function createVM()
  vm = new QuickBrickEpgScreenVM(m.top.riversJson)
  return vm
end function
