import "pkg:/source/login_screen_roku/LoginScreenVM.bs"

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Initialization
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function init()
  m.top.isConsumingOriginEntry = true
  m.top.isForcingMenuHidden = true
  mv.initializeView(m.top.findNode("screenContainer"))
  mv.initializeView(m.top.findNode("labelsGroup"))
  mv.initializeView(m.top.findNode("controlsGroup"))
end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Overridden methods
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function createVM()
  vm = new LoginScreenVM(m.top.riversJson)
  return vm
end function
