import "pkg:/source/quick-brick-login-multi-login-providers/QuickBrickMultiLoginProvidersVM.bs"
import "pkg:/source/roku_modules/maestro/mx/VMTransformFunctions.brs"

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Initialization
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function init()
  m.top.isForcingMenuHidden = true
  initializeView(m.top.findNode("screenContainer"))
end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Overridden methods
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function createVM()
  vm = new QuickBrickMultiLoginProvidersVM(m.top.riversJson)
  return vm
end function
