import "pkg:/source/logout_screen_roku/LogoutScreenVM.bs"

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Initialization
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function init()
  m.top.isConsumingOriginEntry = true
  m.top._styledControlIds = [
    "backgroundRect"
    "labelsGroup"
    "titleText"
    "logoutButton"
  ]

end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Overridden methods
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function createVM()
  vm = new LogoutScreenVM(m.top.riversJson)
  mv.setFocus(m.logoutButton)
  return vm
end function
