import "pkg:/source/logout_screen_roku/LogoutScreenVM.bs"

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Initialization
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function init()
  m.top.isConsumingOriginEntry = true
  m.top._styledControlIds = [
    "backgroundRect"
    "labelsGroup"
    "titleText"
    "logoutButton"
  ] 

end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Overridden methods
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function getControlName()
  return "LogoutScreen"
end function

function createVM()
  vm = new LogoutScreenVM(m.top.riversJson)
  setFocus(m.logoutButton)
  return vm
end function
