'@TestSuite [GTSVMT] GeneraltTextScreenVM Tests
namespace GTSVMT

  '@BeforeEach
  function beforeEach()
    localStore = createObject("roSGNode", "ZSessionStore")
    modelLocator = createObject("roSGNode", "ModelLocator")
    modelLocator.addfields({ "ZPLocalStore": localStore })
    modelLocator.locale = "en"

    zc.TestUtils.setModelLocator(modelLocator)

    riversJson = {
      "id": "generalTextScreen"
      styles: {
      }
    }

    m.vm = new GeneralTextScreenVM(riversJson)
    m.vm.initialize()
  end function

  '@AfterEach
  function afterEach()
    m.global.delete("zapp")
    zc.TestUtils.unsetModelLocator()
  end function

  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  '@It tests onDoneButtonSelected
  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  '@Test 
  function onButtonSelected()
    m.expectOnce(m.vm, "dismiss", ["cancel"])

    m.vm.onButtonSelected(true)

  end function

  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  '@It tests onKeyPressBack
  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  '@Test 
  function onKeyPressBack()
    m.expectOnce(m.vm, "dismiss", ["cancel"])

    m.vm.onKeyPressBack()

  end function

end namespace