import "pkg:/source/gygia_login_screen_roku/ZGygiaLoginScreenVM.bs"

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Initialization
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function init()
  m.top.isConsumingOriginEntry = true
  M_createNodeVars()
  m.groupNames = ["loginGroup", "regcodeGroup"]
  
end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Overridden methods
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function getControlName()
  return "ZGygiaLoginScreen"
end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Overridden
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function createVM()
  return new ZGygiaLoginScreenVM(m.top.riversJson)
end function

function initializeVMBindings()
  logMethod("initializeVMBindings")
  
  MOM_observeField(m.vm, "visibleContentId", onVisibleContentIdChange)
end function

function onVisibleContentIdChange(visibleContentId)
  logInfo("onVisibleContentIdChange", visibleContentId)
  for each groupName in m.groupNames
    m[groupName].visible = groupName = visibleContentId
  end for
end function
