import "pkg:/source/register_screen_roku/RegisterScreenVM.bs"
import "pkg:/source/roku_modules/maestro/mx/VMTransformFunctions.brs"

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Initialization
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function init()
  m.top.isConsumingOriginEntry = true
  m.top.isForcingMenuHidden = true
  mv.initializeView(m.top.findNode("labelsGroup"))
  mv.initializeView(m.top.findNode("controlsGroup"))
  mv.initializeView(m.top.findNode("doneGroup"))
end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Overridden methods
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function createVM()
  vm = new RegisterScreenVM(m.top.riversJson)
  return vm
end function
