import "pkg:/source/adobe-primetime-auth-qb/AdobePrimetimeQuickBrickAuthScreenVM.bs"
import "pkg:/source/roku_modules/maestro/mx/VMTransformFunctions.brs"

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Overridden methods
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function createVM()
  vm = new AdobePrimetimeQuickBrickAuthScreenVM(m.top.riversJson)
  mv.setFocus(m.refreshButton)
  return vm
end function

function onGainedFocus(isSelfFocused)
  if isSelfFocused
    mv.setFocus(m.refreshButton)
  end if
end function