'@TestSuite IPET InplayerEntitlementsTests

namespace InplayerEntitlements.Tests

'@BeforeEach
function beforeEach()
  m.modelLocator = createObject("roSGNode", "ModelLocator")
  
  m.modelLocator = CreateObject("roSGNode", "ModelLocator")
  m.modelLocator.constants = { id: "constants" }
  m.modelLocator.plugins = []
  TU.setModelLocator(m.modelLocator)
  
  'dependencies for testing plugin creation
  
  plugin = BasePlugin(PPMT.CreatePluginJson("1", {
    "client_id": "id1234" 
    "environment": "prod" 
  }))
  m.plugin = new InPlayerEntitlementsPlugin(plugin)
end function

'@AfterEach
function afterEach()
  TU.unsetModelLocator()
  AppService.clearClassInstances()
end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'@It tests constructor
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

'@Test 
'@Params["prod", "123", "AVOD", "none", false, "https://services.inplayer.com"]
'@Params["prod", "123", "SVOD", "none", false, "https://services.inplayer.com"]
'@Params["prod", "1234", "SVOD", "none", false, "https://services.inplayer.com"]
'@Params["dev", "123", "AVOD", "none", false, "https://staging-v2.inplayer.com"]
'@Params["dev", "123", "SVOD", "none", false, "https://staging-v2.inplayer.com"]
'@Params["dev", "1234", "SVOD", "none", false, "https://staging-v2.inplayer.com"]
'@Params["dev", "a123", "AVOD", "authOnly", false, "https://staging-v2.inplayer.com"]
'@Params["dev", "b123", "SVOD", "ICPOnly", true, "https://staging-v2.inplayer.com"]
'@Params["dev", "c1234", "SVOD", "authOrICP", true, "https://staging-v2.inplayer.com"]
'@Params["dev", "d1234", "SVOD", "authAndICP", true, "https://staging-v2.inplayer.com"]
function constructor(env, id, vodModel, entitlementsPolicy, expectedIsUsingRokuStore, expectedUrl)
  plugin = BasePlugin(PPMT.CreatePluginJson("1", {
    "client_id": id
    "environment": env
    "vod_model": vodModel
    "entitlements_policy": entitlementsPolicy 
  }))
  
  plugin = new InPlayerEntitlementsPlugin(plugin)
  
  m.assertEqual(plugin.authenticationData, m.modelLocator.authenticationData)
  m.assertEqual(plugin.apiUrl, expectedUrl)
  m.assertEqual(plugin.vodModel, vodModel)
  m.assertEqual(plugin.entitlementsPolicy, entitlementsPolicy)
  m.assertEqual(plugin.clientId, id)
  m.assertEqual(plugin.isUsingRokuStore, expectedIsUsingRokuStore)
  
end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'@It tests getPurchasedItemIds
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

'@Test not logged in
function getPurchasedItemIds_not_authd()
  m.expectOnce(m.plugin, "getSessionStoreValue", ["inplayer_auth_plugin_roku", "token"], invalid)
  m.assertFalse(m.plugin.getPurchasedItemIds())
end function

'@Test logged in
'@Params[invalid, []]
'@Params[{}, []]
'@Params[[], []]
'@Params[[{}], []]
'@Params[[{"errors": {"401": "Invalid auth Token"}}], []]
'@Params[[{external_fees:invalid}], []]
'@Params[[{external_fees:[{external_id: invalid}]}], []]
'@Params[[{external_fees:[{external_id: "1"}]}], ["1"]]
'@Params[[{external_fees:[{external_id: "1"},{external_id: "2"}]}], ["1"]]
'@Params[[{external_fees:[{external_id: "1"},{external_id: "2"}]}, {external_fees:[{external_id: "3"}]}], ["1", "3"]]
function getPurchasedItemIds_invalidScenarios(response, expectedIds) as void
  m.expectOnce(m.plugin, "getSessionStoreValue", ["inplayer_auth_plugin_roku", "token"], "t")
  m.expectOnce(m.plugin, "executeAPIRequest", ["GET", "items/access/customers?status=active", invalid, true, "t"], response)
  
  result = m.plugin.getPurchasedItemIds()
  m.assertArrayContainsSubset(result, expectedIds)
  
end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'@It tests post purchases
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

'@Test post Purchases - no failures
'@Params[[], true]
'@Params[[{"error": "here"}], false]
function getEntitlements_postPurchases(response, expectedResult) as void
  rokuPurchases = {}
  m.expectOnce(m.plugin, "sendPurchasesToInPlayer", [rokuPurchases], response)
  
  result = m.plugin.postPurchases(rokuPurchases)
  m.assertEqual(result, expectedResult)
end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'@It tests getAvailableProducts
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

'@Test invalid scenarios
'@Params[invalid, invalid]
'@Params["t", invalid]
'@Params[invalid, {"id": "1"}]
function getAvailableProducts_not_valid(token, item)
  rokuCatalogItems = [RCSMT_CreateRokuCatalogItem("1"), RCSMT_CreateRokuCatalogItem("2"), RCSMT_CreateRokuCatalogItem("3")]
  currentSelection = { id: "currentSelection", "currentItem": item }
  
  m.expectOnce(m.plugin, "getInstance", ["currentSelection"], currentSelection)
  m.expectOnce(m.plugin, "getSessionStoreValue", ["inplayer_auth_plugin_roku", "token"], token)
  
  m.modelLocator.availableProducts.availableProducts = ["something"]
  m.plugin.getAvailableProducts(rokuCatalogItems, ["1"])
  m.assertEmpty(m.modelLocator.availableProducts.availableProducts)
  
end function

'@Test valid scenarios
'@Params[[], []]
'@Params[["1"], ["1"]]
'@Params[["1", "2"], ["1", "2"]]
'@Params[["1", "2", "3"], ["1", "2", "3"]]
'@Params[["4", "2", "3"], [2", "3"]]
'@Params[["4", "5", "6"], []]
function getAvailableProducts_valid(feeIds, expectedIds)
  rokuCatalogItems = [RCSMT_CreateRokuCatalogItem("1"), RCSMT_CreateRokuCatalogItem("2"), RCSMT_CreateRokuCatalogItem("3")]
  item = { id: "item" }
  currentSelection = { id: "currentSelection", "currentItem": item }
  
  m.expectOnce(m.plugin, "getInstance", ["currentSelection"], currentSelection)
  m.expectOnce(m.plugin, "getSessionStoreValue", ["inplayer_auth_plugin_roku", "token"], "t")
  
  m.modelLocator.availableProducts.availableProducts = ["something"]
  
  m.expectOnce(m.plugin, "getInPlayerFeeIdsForItem", [item, "t"], feeIds)
  
  
  m.plugin.getAvailableProducts(rokuCatalogItems, purchasedIds)
  
  products = m.modelLocator.availableProducts.availableProducts
  m.assertArrayCount(products, expectedIds.count())
  
  productIds = []
  for each product in products
    productIds.push(product.code)
  end for
  
  m.assertArrayContainsSubset(productIds, expectedIds)
  
end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'@It tests loaItem
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

'@Test noToken
function loadItem_noToken()
  m.expectOnce(m.plugin, "getSessionStoreValue", ["inplayer_auth_plugin_roku", "token"], invalid)
  
  item = { 
    id: "item"
    extensions: {
      external_id: "xid"
    }
  }
  m.assertFalse(m.plugin.loadItem(item))
  
end function

'@Test invalid item
'@Params[invalid]
'@Params[{"id":"item"}]
'@Params[{"id":"item", extensions: invalid}]
'@Params[{"id":"item", extensions: {"other": true}}]
'@Params[{"id":"item", extensions: {"external_id": invalid}}]
function loadItem_invalid_item(item)
  m.expectOnce(m.plugin, "getSessionStoreValue", ["inplayer_auth_plugin_roku", "token"], "t")
  m.assertFalse(m.plugin.loadItem(item))
end function

'@Test valid
function loadItem_valid()
  m.expectOnce(m.plugin, "getSessionStoreValue", ["inplayer_auth_plugin_roku", "token"], "t")
  item = createObject("roSGNode", "Node")
  item.addFields({ 
    id: "item"
    extensions: {
      external_id: "xid"
    }
    url: "ourl"
  })
  
  
  result = { 
    id: "result"
    item: {
      content: formatJson({ mobile_url: "changedUrl" })
    }
  }
  m.expectOnce(m.plugin, "executeAPIRequest", ["POST", "items/xid/access", invalid, true, "t"], result)
  
  m.assertTrue(m.plugin.loadItem(item))
  
  m.assertInvalid(item.error)
  m.assertEqual(item.originalUrl, "ourl")
  m.assertEqual(item.url, "changedUrl")
  
end function

'@Test server errors
'@Params[invalid, "Error loading item: item title"]
'@Params[{}, "Error loading item: item title"]
'@Params[{errors:invalid]}, "Error loading item: item title"]
'@Params[{errors:{}]}, "Error loading item: item title"]
'@Params[{errors:{"401":"custom error"}}, "custom error"]
function loadItem_errors(result, expectedErrorMessage)
  m.expectOnce(m.plugin, "getSessionStoreValue", ["inplayer_auth_plugin_roku", "token"], "t")
  item = createObject("roSGNode", "Node")
  item.addFields({ 
    id: "item"
    title: "item title"
    extensions: {
      external_id: "xid"
    }
    url: "ourl"
  })
  
  m.expectOnce(m.plugin, "executeAPIRequest", ["POST", "items/xid/access", invalid, true, "t"], result)
  
  m.assertFalse(m.plugin.loadItem(item))
  
  m.assertEqual(item.errorMessage, expectedErrorMessage)
  m.assertInvalid(item.originalUrl)
  m.assertEqual(item.url, "ourl")
  
end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'@It tests getEntitlements
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++



end namespace