import "pkg:/source/regcode_login_screen_roku/RegcodeLoginScreenVM.bs"

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Initialization
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function init()
  m.top.isConsumingOriginEntry = true
  M_createNodeVars() 

end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'++ Overridden methods
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function getControlName()
  return "RegcodeLoginScreen"
end function

function createVM()
  vm = new RegcodeLoginScreenVM(m.top.riversJson)
  setFocus(m.refreshButton)
  return vm
end function

function onGainedFocus(isSelfFocused)
  if isSelfFocused
    setFocus(m.refreshButton)
  end if
end function